#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();
require __DIR__.'/src/App.php';

$console = require __DIR__.'/src/Console.php';
$console->run();
